hawkeye:
  cluster:
    clusterName: test1
    registryAddress: 0.0.0.0:2181
  executor:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 100
logging:
  config: classpath:logback.xml
server:
  port: 8882